version: '3.8'
services:
  h2-db:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "1521:1521"
      - "8082:8082"
    volumes:
      - ./h2data:/opt/h2-data
    environment:
      - H2_OPTIONS=-ifNotExists
    restart: always