services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    restart: always
    environment:
      # MariaDB도 MySQL과 환경 변수명이 동일하게 호환됩니다.
      MARIADB_ROOT_PASSWORD: qwer1234!
      MARIADB_DATABASE: rootmb
      MARIADB_USER: user
      MARIADB_PASSWORD: qwer1234!
    ports:
      - "3306:3306"  # 기존 MySQL(3306)과 충돌을 피하기 위해 호스트 포트를 3307로 설정
    volumes:
      - ./mariadb/data:/var/lib/mysql