services:
  mariadb:
    container_name: "my_mariadb"
    image: "mariadb:11.4"  # 현재 안정적인 최신 버전 중 하나입니다.
    restart: "always"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"  # 기존 MySQL(3306)과 동시에 띄울 수 있게 3307로 변경했습니다.
    environment:
      MARIADB_ROOT_PASSWORD: "root1234@"
      TZ: "Asia/Seoul"
    volumes:
      - ./mariadb-data:/var/lib/mysql